# Tests out the post to mastodon action
name: Post to Mastodon
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Post to Mastodon
      uses: ./
      with:
        instance: 'https://cosocial.ca'
        token: ${{ secrets.MASTODON_TOKEN }}
        status: Hello, World! With 'single quotes' and "double quotes"!
        visibility: 'private'
